#!/usr/bin/env node
/**
 * Proves the committed photo assets match photos-src/ and the pipeline.
 *
 * The images are generated by scripts/optimize-photos.mjs and committed rather
 * than built on the deploy. That is deliberate: `npm run typecheck` reads
 * src/lib/photos.generated.ts, and it runs before the build in CI, so a
 * manifest that only exists after `next build` would fail the job before it
 * was ever written. Generating at deploy time would also mean paying for sharp
 * on every release to produce byte-identical files.
 *
 * The cost of committing generated output is drift: someone drops a new JPEG
 * into photos-src/, forgets `npm run photos:build`, and the site ships without
 * it — or worse, ships a stale version of a replaced photograph. This closes
 * that hole. Every source file must be registered in the pipeline, and every
 * registered photo must have every rendition its manifest claims.
 */
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = new URL('..', import.meta.url).pathname;
const SRC_DIR = join(ROOT, 'photos-src');
const OUT_DIR = join(ROOT, 'public', 'photos');
const MANIFEST = join(ROOT, 'src', 'lib', 'photos.generated.ts');
const PIPELINE = join(ROOT, 'scripts', 'optimize-photos.mjs');

const errors = [];

const sources = readdirSync(SRC_DIR)
  .filter((f) => f.endsWith('.jpg'))
  .map((f) => f.replace(/\.jpg$/, ''));

const pipeline = readFileSync(PIPELINE, 'utf8');
const manifest = readFileSync(MANIFEST, 'utf8');

for (const name of sources) {
  if (!pipeline.includes(`name: '${name}'`)) {
    errors.push(`photos-src/${name}.jpg is not registered in optimize-photos.mjs`);
    continue;
  }
  if (!manifest.includes(`"${name}"`)) {
    errors.push(`${name} is registered but missing from the manifest — run npm run photos:build`);
  }
}

// Every width the manifest promises must exist on disk in both formats.
for (const [, name, widths] of manifest.matchAll(/"([\w-]+)": \{[^}]*?"widths": \[([^\]]*)\]/gs)) {
  for (const width of widths.match(/\d+/g) ?? []) {
    for (const ext of ['avif', 'webp']) {
      const file = join(OUT_DIR, `${name}-${width}.${ext}`);
      if (!existsSync(file)) errors.push(`missing ${name}-${width}.${ext} — run npm run photos:build`);
    }
  }
}

// A source edited after its output was written means the output is stale.
for (const name of sources) {
  const src = join(SRC_DIR, `${name}.jpg`);
  const out = join(OUT_DIR, `${name}-480.avif`);
  if (!existsSync(out)) continue;
  if (statSync(src).mtimeMs > statSync(out).mtimeMs + 1000) {
    errors.push(`photos-src/${name}.jpg is newer than its output — run npm run photos:build`);
  }
}

if (errors.length) {
  console.error(`\n  ${errors.length} photo problem(s):\n`);
  for (const e of errors) console.error(`    ${e}`);
  console.error('');
  process.exit(1);
}

console.log(`  check-photos: ${sources.length} sources, all built and current`);
