import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

/**
 * Build-time image pipeline.
 *
 * §7 sets the constraints this exists to satisfy: a landing page under 300 KB,
 * a first paint under two seconds on 3G, and usable on a low-end Android. That
 * rules out shipping source JPEGs and it rules out an on-demand image service
 * (which would also break the static-CDN requirement). So every size and format
 * is produced here, once, and served as a plain file.
 *
 * Run with `npm run photos:build` after adding or replacing a source image.
 */
const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const WIDTHS = [480, 768, 1200, 1800];

/** Each photo earns its place by carrying one line of the charter. */
const PHOTOS = [
  { name: 'olive', aspect: 3 / 2, meaning: 'The olive of the mark; peace as a living thing.' },
  { name: 'earth', aspect: 16 / 9, meaning: '"The whole world is one country."' },
  { name: 'reach', aspect: 3 / 2, meaning: 'Two parties reaching; neither reaching further.' },
  { name: 'offer', aspect: 3 / 2, meaning: 'Open hands: what each party is willing to give.' },
];

/**
 * One treatment across every photo, so a page of them reads as one set rather
 * than as four stock pictures: saturation pulled back, warmth lifted a little
 * towards the olive and gold of the palette.
 */
const cohere = (pipeline) => pipeline.modulate({ saturation: 0.86, brightness: 1.02 }).gamma(1.02);

async function build() {
  const outDir = join(ROOT, 'public', 'photos');
  await mkdir(outDir, { recursive: true });
  const manifest = {};

  for (const photo of PHOTOS) {
    const source = await readFile(join(ROOT, 'photos-src', `${photo.name}.jpg`));
    const meta = await sharp(source).metadata();
    const sources = { avif: [], webp: [] };

    for (const width of WIDTHS) {
      if (width > (meta.width ?? 0)) continue;
      const resized = cohere(sharp(source).resize({ width, withoutEnlargement: true }));

      const avif = await resized.clone().avif({ quality: 52, effort: 6 }).toBuffer();
      const webp = await resized.clone().webp({ quality: 72 }).toBuffer();
      await writeFile(join(outDir, `${photo.name}-${width}.avif`), avif);
      await writeFile(join(outDir, `${photo.name}-${width}.webp`), webp);

      sources.avif.push({ width, bytes: avif.byteLength });
      sources.webp.push({ width, bytes: webp.byteLength });
    }

    // A 20px blur, inlined, so the layout never jumps and something is on
    // screen immediately on a slow connection.
    const blur = await cohere(sharp(source).resize({ width: 20 })).webp({ quality: 40 }).toBuffer();

    manifest[photo.name] = {
      aspect: photo.aspect,
      meaning: photo.meaning,
      widths: sources.avif.map((entry) => entry.width),
      blurDataUrl: `data:image/webp;base64,${blur.toString('base64')}`,
    };

    const largest = sources.avif.at(-1);
    console.log(`  ${photo.name.padEnd(6)} ${sources.avif.length} sizes, largest AVIF ${Math.round((largest?.bytes ?? 0) / 1024)} KB`);
  }

  const file =
    `// Generated by scripts/optimize-photos.mjs — do not edit by hand.\n` +
    `// Run \`npm run photos:build\` after changing anything in photos-src/.\n\n` +
    `export interface PhotoAsset {\n  aspect: number;\n  meaning: string;\n  widths: number[];\n  blurDataUrl: string;\n}\n\n` +
    `export const PHOTOS = ${JSON.stringify(manifest, null, 2)} as const satisfies Record<string, PhotoAsset>;\n\n` +
    `export type PhotoName = keyof typeof PHOTOS;\n`;

  await writeFile(join(ROOT, 'src', 'lib', 'photos.generated.ts'), file);
  console.log('  manifest written to src/lib/photos.generated.ts');
}

await build();
