// Generated by scripts/optimize-photos.mjs — do not edit by hand.
// Run `npm run photos:build` after changing anything in photos-src/.

export interface PhotoAsset {
  aspect: number;
  meaning: string;
  widths: number[];
  blurDataUrl: string;
}

export const PHOTOS = {
  "olive": {
    "aspect": 1.5,
    "meaning": "The olive of the mark; peace as a living thing.",
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "blurDataUrl": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAAAwBQCdASoUAB4APu1mqk2ppaQiMAgBMB2JZwC+wBuslMzUY7tSOGEaM87b9v71Vut0AAD+5D9Bn6Mr9pM/UUcQSvqS3FF7uilwAYTZ817UkumS6E8MN1linjyWQfET1XGRvrHc2x8uK+MgH000HkVkAuS73CpMNxqkyuive2gLPlQlr6BlJmXbpKkdHhyuNb/O9BeCRG/turg/WxZAWblVCGCx79dGsnVa03J6dlIlttIpEMAAAA=="
  },
  "earth": {
    "aspect": 1.7777777777777777,
    "meaning": "\"The whole world is one country.\"",
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "blurDataUrl": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAwBACdASoUAAsAPu1iqk2ppaQiMAgBMB2JYwCdMoACj24gf3ZrMcmBUAAA/vDfDRnm5kEWU5x/OIg69pQqHlwuTIgWEWa7Bg/V7QlVZm9Ee5WJrI5I4PlEP1TGqiTYto3JtFemAAAAAA=="
  },
  "reach": {
    "aspect": 1.5,
    "meaning": "Two parties reaching; neither reaching further.",
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "blurDataUrl": "data:image/webp;base64,UklGRjYBAABXRUJQVlA4ICoBAACwBgCdASoUAB4APu1iqU2ppaOiMAgBMB2JQBgh5g8IaR+WbpAmehS8adcprgSP0M8m2MHMfvUp+i+jKvUygAD+Vdr9rKvimuVm0g12Oml3Y1dNHCZueoKCZhaEFtWskEdpKcBQ9cLYxiAwSUUudraA1euHSRnHaxelyLY50OO7nuWhVnvNSww+6dfe/FP2WHZ4dP50+qPwgH3trK6ymil3JL5gh2YJaUokgASj+9AhzsB0XpRM7IKl9Bfl3ZDfZqEL9oFI+v9z+ImIRSDP5xs9BeKpH8VqKeUkK2jVs1lHIXb8G4vchmjJ9MaDkgrGsT2U6LHTb1zJbc9frQmoxWMSJ4TyyBqX/S+CjYSSrXmHLmj3/BKGxkOW4OhDamryK/8cD/o61syI9HAA"
  },
  "offer": {
    "aspect": 1.5,
    "meaning": "Open hands: what each party is willing to give.",
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "blurDataUrl": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABQBACdASoUAA4APu1kqU2ppaQiMAgBMB2JYwC7Ef/gPI+zgIk3ErkaaPAAAP7wxHkZa2j9jWnAbn0NQBbZavyqi8iRDq864LFK5uWGJji7sq6ij2i2swqqdyJyNFv+DVl5P0AqyGXzIR+iUiHgjZScwAA="
  }
} as const satisfies Record<string, PhotoAsset>;

export type PhotoName = keyof typeof PHOTOS;
