// Generated by scripts/optimize-photos.mjs — do not edit by hand.
// Run `npm run photos:build` after changing anything in photos-src/.

export interface PhotoAsset {
  aspect: number;
  meaning: string;
  widths: number[];
  blurDataUrl: string;
}

export const PHOTOS = {
  "olive": {
    "aspect": 1.5,
    "meaning": "The olive of the mark; peace as a living thing.",
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "blurDataUrl": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAAAwBQCdASoUAB4APu1mqk2ppaQiMAgBMB2JZwC+wBuslMzUY7tSOGEaM87b9v71Vut0AAD+5D9Bn6Mr9pM/UUcQSvqS3FF7uilwAYTZ817UkumS6E8MN1linjyWQfET1XGRvrHc2x8uK+MgH000HkVkAuS73CpMNxqkyuive2gLPlQlr6BlJmXbpKkdHhyuNb/O9BeCRG/turg/WxZAWblVCGCx79dGsnVa03J6dlIlttIpEMAAAA=="
  },
  "earth": {
    "aspect": 1.7777777777777777,
    "meaning": "\"The whole world is one country.\"",
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "blurDataUrl": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAwBACdASoUAAsAPu1iqk2ppaQiMAgBMB2JYwCdMoACj24gf3ZrMcmBUAAA/vDfDRnm5kEWU5x/OIg69pQqHlwuTIgWEWa7Bg/V7QlVZm9Ee5WJrI5I4PlEP1TGqiTYto3JtFemAAAAAA=="
  },
  "reach": {
    "aspect": 1.5,
    "meaning": "Two parties reaching; neither reaching further.",
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "blurDataUrl": "data:image/webp;base64,UklGRjYBAABXRUJQVlA4ICoBAACwBgCdASoUAB4APu1iqU2ppaOiMAgBMB2JQBgh5g8IaR+WbpAmehS8adcprgSP0M8m2MHMfvUp+i+jKvUygAD+Vdr9rKvimuVm0g12Oml3Y1dNHCZueoKCZhaEFtWskEdpKcBQ9cLYxiAwSUUudraA1euHSRnHaxelyLY50OO7nuWhVnvNSww+6dfe/FP2WHZ4dP50+qPwgH3trK6ymil3JL5gh2YJaUokgASj+9AhzsB0XpRM7IKl9Bfl3ZDfZqEL9oFI+v9z+ImIRSDP5xs9BeKpH8VqKeUkK2jVs1lHIXb8G4vchmjJ9MaDkgrGsT2U6LHTb1zJbc9frQmoxWMSJ4TyyBqX/S+CjYSSrXmHLmj3/BKGxkOW4OhDamryK/8cD/o61syI9HAA"
  },
  "offer": {
    "aspect": 1.5,
    "meaning": "Open hands: what each party is willing to give.",
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "blurDataUrl": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAABQBACdASoUAA4APu1kqU2ppaQiMAgBMB2JYwC7Ef/gPI+zgIk3ErkaaPAAAP7wxHkZa2j9jWnAbn0NQBbZavyqi8iRDq864LFK5uWGJji7sq6ij2i2swqqdyJyNFv+DVl5P0AqyGXzIR+iUiHgjZScwAA="
  },
  "horizon": {
    "aspect": 0.8,
    "meaning": "A level horizon: the one line with nothing above anything.",
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "blurDataUrl": "data:image/webp;base64,UklGRmgAAABXRUJQVlA4IFwAAACQAwCdASoUAA0APu1iqk2ppaQiMAgBMB2JZQAATu6eTCRwX90AAPFGX0OpISBL7HrzEnaOF25P7cchweD4FXBISCRIebvNlwpJkIHW3TA4/wfN+94U0zvIHsgAAA=="
  },
  "path": {
    "aspect": 0.8,
    "meaning": "A path anyone may walk. No gate and no one at it.",
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "blurDataUrl": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACwAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JZQC7ACKfCI/9mK2JWAD+36Dpba7x/sbRXnwwlRnQRuh65NdiuqqfKyMCz883kqhLVAQ2fM4UfYVlpAJqqdKAzLkPBAwv9Rt1eajEAAA="
  },
  "reflection": {
    "aspect": 0.8,
    "meaning": "Still water: whatever one side has, the other has exactly.",
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "blurDataUrl": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAADwAwCdASoUAA8APu1iqU2ppaOiMAgBMB2JZwAAYXQOimtm40xSZ9wAAP6N32Tv1mnGoNiSezmldunZiKAtKcgcdFyJaRI+Uiz2XAFQrcxJz5/LNYmZJtKymsmm2FSR7ZTQbO66iNRKAvRgAAA="
  },
  "vision-creation": {
    "aspect": 0.8,
    "meaning": "The Pillars of Creation: matter becoming stars.",
    "widths": [
      480,
      768
    ],
    "blurDataUrl": "data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAABwBACdASoUABkAPu1qrVEppaQiqAqpMB2JZwAAI4i6yN9o2iSKS3xBveykNAD+3GoMMtq9MBd2oVfFz0OAIgY2yhql/HZr9206ygnd4ns0g696ozixYuG14PggumbJtFVpFsDvN7quZjHiBkrNWCwwPT0DTQAA"
  },
  "vision-nerveCell": {
    "aspect": 0.8,
    "meaning": "Purkinje neurons, the branching the statement is about.",
    "widths": [
      480,
      768,
      1200
    ],
    "blurDataUrl": "data:image/webp;base64,UklGRsIAAABXRUJQVlA4ILYAAAAwBQCdASoUABkAPu1sq1EppaOiqAqpMB2JZwAD5UEaeg9J20Ui09iXBiql1YVfApDMAAD9nXWuzwIzCGHZUCzNtD7mAx0wijslsYxQQfGYEnPjhu5ZDnWnO5xSC/knl9NvuZk5z7l6AXDtprk86F5G51c8L3PK1SzGnTrC0Q9yNLu0nkf/rxXEExA201gTV5VOfUqoyAuhOYMN2dyieFdy8uZqBWbAA4nZEQR2P2/SVPHggukIAA=="
  },
  "vision-purpose": {
    "aspect": 0.8,
    "meaning": "Scaffolding: the universe still being built.",
    "widths": [
      480,
      768,
      1200,
      1800
    ],
    "blurDataUrl": "data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADwBACdASoUABkAPu1qrVCppaQiqAqpMB2JZwDO7BEcZn14tel546mc7WSIejWgC/AA/sOR6da0cDJ9u/yMEsa2DG44RWsWVKYOLe6XoWoHLbjUueSVdyVuntMqcISu7WL0PHRVAy6280g2Yp0IdAsOb2WPZ/gFc7RvPdEdPQmyKqWCp+npKAdw4uCrpXxgAAA="
  },
  "vision-religionAndScience": {
    "aspect": 0.8,
    "meaning": "A nautilus: one object that is both wonder and mathematics.",
    "widths": [
      480,
      768
    ],
    "blurDataUrl": "data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAABQBACdASoUABkAPu1irU+ppSQiMBgIATAdiWcAABQw2kzXw0sf6A/JF0AAAOcZReBYYwIK9Az3EeUkbffJ/ZOEogf7zKZmJ4EY754aIBudG8/dLdMbBx2ju2lvlaFDmufpHll0gAAAAA=="
  },
  "vision-humanity": {
    "aspect": 0.8,
    "meaning": "A murmuration: thousands of equals moving as one body.",
    "widths": [
      480,
      768
    ],
    "blurDataUrl": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAADwBACdASoUABkAPu1sq1EppaOiqAqpMB2JZwDE2auEFoHRm0oaIi3tycwhA8T/UAAA/tmKNMnkfVYCpClYtr5SChkFEEXh5371CBoqU53ceNZuQ3SvL0J3PSixinsRFI3vInGjo/L6WDWW5wPZPH48CBG9GkX49ksvBsfasSziCZVoYwl5b/9whcAQmUuOu51MDWrAAAA="
  },
  "vision-oneCountry": {
    "aspect": 0.8,
    "meaning": "Earthrise: not one border is visible from there.",
    "widths": [
      480,
      768,
      1200
    ],
    "blurDataUrl": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQBACdASoUABkAPulkq02pJaQiMBgMASAdCWcAyrQQ7+D0fb5SoPLXa0rLVl+ikAD+68qDAKhh4sD+uU04btgtJS1loCPZkR6u0W4bxC0liYyBEg7aYoQ/RfBvGbpUo8Ortt+UgAA="
  },
  "vision-shortLife": {
    "aspect": 0.8,
    "meaning": "A dandelion clock, one breath from gone.",
    "widths": [
      480,
      768
    ],
    "blurDataUrl": "data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAABwBQCdASoUABkAPu1ur1KppiQiqAgBMB2JZwDMHBDdvM8kZ8hJ4+1xDSUrUTjy50UDrcQAAP7LWzDKKFA0ft/7zY+16qnW/lHdeC/j5fiHSwFH+vAz0DXFe2+LJ+4EbD2I0mwfL9k4Me6HlqdXB0mLmNMZATNrMHG9CnHTBNGqUqaRhIsR+u/Wj4AAAAAA"
  }
} as const satisfies Record<string, PhotoAsset>;

export type PhotoName = keyof typeof PHOTOS;
